services:
    ing-db:
        container_name: "ing-db"  
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1434:1433"
        hostname: ing-sql-server
        volumes:
            - sqlvolume:/var/opt/mssql
        environment:
            - "ACCEPT_EULA=Y"
            - "MSSQL_SA_PASSWORD=${SA_PASSWORD}"    
    ing-backend:
        container_name: "ing-backend"
        build: .
        ports:
            - "34003:8080"
        environment:
            - DOCKER_HOST=true
            - "SA_PASSWORD=${SA_PASSWORD}"
        depends_on: 
            - ing-db

volumes:    
    sqlvolume:
        
